<?php

function scald_migrate_node_update($node) {
  _scald_migrate_image_migrate($node);
}

function _scald_migrate_image_migrate($node) {
  if (FALSE == $image_info = _scald_migrate_check_node($node)) {
    return;
  }

  if (!empty($node->field_image_atom)) {
    return;
  }

  $atom = _scald_migrate_build_atom($image_info);

  $sid = scald_atom_save($atom);

  $node_wrapper = entity_metadata_wrapper('node', $node);

  if ($sid != FALSE) {
    $node_wrapper->field_image_atom->set($sid);
  }
}

function _scald_migrate_check_node($node) {
  $node_types = array(
    'case_study',
    'page',
    'promo',
  );

  $node_fields = array(
    'field_page_image',
    'field_promo_image',
  );

  // Check if node is proper node type
  if (!in_array($node->type, $node_types)) {
    return FALSE;
  }

  // If the node has an image field, set it to image_field
  $image_field = NULL;

  foreach ($node_fields as $node_field) {
    if (property_exists($node, $node_field)) {
      $image_field = $node->$node_field;
    }
  }

  // If there was no image field, return
  if ($image_field == NULL) {
    return FALSE;
  }

  // Check to see if the image field has an image
  if (empty($image_field)) {
    return FALSE;
  }
  else {
    $image_info = array(
      'file_field' => $image_field,
      'file' => file_load($image_field['und'][0]['fid']),
    );

    return $image_info;
  }
}

function _scald_migrate_build_atom(array $image_info) {
  $atom = new stdClass();

  $atom->type = 'image';
  $atom->provider = 'scald_image';
  $atom->publisher = 1;
  $atom->language = 'und';
  $atom->actions = 5;
  $atom->title = ucwords(str_replace('_',' ',basename($image_info['file']->filename)));
  $atom->base_id = $image_info['file']->fid;

  $atom->scald_thumbnail['und'][0]['fid'] = $image_info['file']->fid;
  $atom->scald_thumbnail['und'][0]['display'] = '1';
  $atom->scald_thumbnail['und'][0]['width'] = $image_info['file_field']['und'][0]['width'];
  $atom->scald_thumbnail['und'][0]['height'] = $image_info['file_field']['und'][0]['height'];
  $atom->scald_thumbnail['und'][0]['description'] = '';
  $atom->scald_thumbnail['und'][0]['upload_button'] = 'Upload';
  $atom->scald_thumbnail['und'][0]['remove_button'] = 'Remove';
  $atom->scald_thumbnail['und'][0]['upload'] = '';
  $atom->scald_thumbnail['und'][0]['alt'] = $atom->title;
  $atom->scald_thumbnail['und'][0]['title'] = $atom->title;

  return $atom;
}